name: Symfony Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          tools: composer:v2

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer dependencies
        run: composer install --no-progress --no-scripts --prefer-dist --working-dir=app/symfony

      - name: Check installed dependencies
        run: ls -la app/symfony/vendor/bin/

      - name: Run PHP_CodeSniffer with PHP-CS-Fixer
        run: php app/symfony/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run

      - name: Run PHPStan
        run: php app/symfony/vendor/bin/phpstan analyse --configuration=phpstan.dist.neon

      - name: Run phpunit
        run: php app/symfony/vendor/bin/phpunit --configuration=phpunit.xml.dist